// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20210122232323_ResetMigrationNewProjectName")]
    partial class ResetMigrationNewProjectName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.NatlPark", b =>
                {
                    b.Property<int>("NatlParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("NatlParkId");

                    b.ToTable("NatlParks");

                    b.HasData(
                        new
                        {
                            NatlParkId = 1,
                            Name = "Crater Lake National Park",
                            State = "Oregon"
                        });
                });

            modelBuilder.Entity("ParksApi.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 1,
                            Name = "Silver Falls State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            StateParkId = 2,
                            Name = "Fort Stevens State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            StateParkId = 3,
                            Name = "Cape Lookout State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            StateParkId = 4,
                            Name = "Smith Rock State Park",
                            State = "Oregon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
